# catch-microservice task-build-push.yml

platform: linux

# DOCKER BASE IMAGE FOR TASKS (BASED ON ALPINE, A SMALLER LINUX DISTRIBUTION)
image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.20.1

inputs:
  - name: catch-microservice

outputs:
  - name: dist

run:
  path: ./catch-microservice/ci/scripts/build-push.sh
  # args: [-debug]
