# catch-microservice task-readme-github-pages.yml

platform: linux

# DOCKER BASE IMAGE FOR TASKS (BASED ON ALPINE, A SMALLER LINUX DISTRIBUTION)
image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.20.1

inputs:
  - name: catch-microservice

outputs:
  - name: catch-microservice-updated

run:
  path: ./catch-microservice/ci/scripts/readme-github-pages.sh
  # args: [-debug]
