# catch-microservice task-unit-tests.yml

platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang
    tag: 1.7.1

inputs:
- name: catch-microservice

outputs:
- name: coverage-results

run:
  path: ./catch-microservice/ci/scripts/unit-tests.sh
